name = "statuspage-worker"
main = "./src/index.ts"
compatibility_date = "2022-05-20"
account_id = 'd059d559b54c11f29d0b573ee9509f77'
workers_dev = true

# Duplicate preview_id to id
kv_namespaces = [
   { binding = "KV_STATUS_PAGE",  id = "247e3b24ad8e4650acff43b2dc456ea7" }
]
# Run `wrangler publish --env production` when happy
[env.production]
kv_namespaces = [
   { binding = "KV_STATUS_PAGE", id = "247e3b24ad8e4650acff43b2dc456ea7" }
]
# MPknq58FHUiUPI2p5ISiSKQ2Td8kugv0gaPZQ3MG